# Generated by Django 5.2.6 on 2025-09-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('new', 'New'), ('apparel', 'Apparel'), ('kids', 'Kids'), ('brands', 'Brands'), ('footwear', 'Footwear'), ('equipment', 'Equipment'), ('sale', 'Sale')], default='new', max_length=20),
        ),
    ]
